export const SET_USER = 'SET_USER';
// export const SET_CURRENT_CATEGORY = 'SET_CURRENT_CATEGORY';
// export const CALCULATE_CATEGORY_POSITION = 'CALCULATE_CATEGORY_POSITION';
// export const CALCULATE_CATEGORY_RADIUS = 'CALCULATE_CATEGORY_RADIUS';
// export const SET_CATEGORY_COLOR = 'SET_CATEGORY_COLOR';
// export const CATEGORY_HOVER = 'CATEGORY_HOVER';
// export const SET_CURRENT_LISTING = 'SET_CURRENT_LISTING';
// export const DELETE_LISTING = 'DELETE_LISTING';
// export const ADD_LISTING = 'ADD_LISTING';
// export const SHOW_MODAL = 'SHOW_MODAL';
// export const CREATE_CONTRACT = 'CREATE_CONTRACT';
// export const SIGN_CONTRACT = 'SIGN_CONTRACT';

